// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PragueParkingDataAccess;

#nullable disable

namespace WpfAppDataAccess.Migrations
{
    [DbContext(typeof(ParkingContext))]
    [Migration("20220426170408_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("PragueParkingDataAccess.ParkingGarage", b =>
                {
                    b.Property<int>("GarageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GarageId"), 1L, 1);

                    b.HasKey("GarageId");

                    b.ToTable("Garages");

                    b.HasData(
                        new
                        {
                            GarageId = 1
                        });
                });

            modelBuilder.Entity("PragueParkingDataAccess.ParkingSpot", b =>
                {
                    b.Property<int>("ParkingSpotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ParkingSpotId"), 1L, 1);

                    b.Property<int>("ParkingGarageId")
                        .HasColumnType("int");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.HasKey("ParkingSpotId");

                    b.HasIndex("ParkingGarageId");

                    b.ToTable("ParkingSpots");

                    b.HasData(
                        new
                        {
                            ParkingSpotId = 1,
                            ParkingGarageId = 1,
                            Size = 4
                        },
                        new
                        {
                            ParkingSpotId = 2,
                            ParkingGarageId = 1,
                            Size = 4
                        },
                        new
                        {
                            ParkingSpotId = 3,
                            ParkingGarageId = 1,
                            Size = 4
                        },
                        new
                        {
                            ParkingSpotId = 4,
                            ParkingGarageId = 1,
                            Size = 4
                        },
                        new
                        {
                            ParkingSpotId = 5,
                            ParkingGarageId = 1,
                            Size = 4
                        },
                        new
                        {
                            ParkingSpotId = 6,
                            ParkingGarageId = 1,
                            Size = 4
                        },
                        new
                        {
                            ParkingSpotId = 7,
                            ParkingGarageId = 1,
                            Size = 4
                        },
                        new
                        {
                            ParkingSpotId = 8,
                            ParkingGarageId = 1,
                            Size = 4
                        },
                        new
                        {
                            ParkingSpotId = 9,
                            ParkingGarageId = 1,
                            Size = 4
                        },
                        new
                        {
                            ParkingSpotId = 10,
                            ParkingGarageId = 1,
                            Size = 4
                        },
                        new
                        {
                            ParkingSpotId = 11,
                            ParkingGarageId = 1,
                            Size = 4
                        },
                        new
                        {
                            ParkingSpotId = 12,
                            ParkingGarageId = 1,
                            Size = 4
                        },
                        new
                        {
                            ParkingSpotId = 13,
                            ParkingGarageId = 1,
                            Size = 4
                        },
                        new
                        {
                            ParkingSpotId = 14,
                            ParkingGarageId = 1,
                            Size = 4
                        },
                        new
                        {
                            ParkingSpotId = 15,
                            ParkingGarageId = 1,
                            Size = 4
                        },
                        new
                        {
                            ParkingSpotId = 16,
                            ParkingGarageId = 1,
                            Size = 4
                        },
                        new
                        {
                            ParkingSpotId = 17,
                            ParkingGarageId = 1,
                            Size = 4
                        },
                        new
                        {
                            ParkingSpotId = 18,
                            ParkingGarageId = 1,
                            Size = 4
                        },
                        new
                        {
                            ParkingSpotId = 19,
                            ParkingGarageId = 1,
                            Size = 4
                        },
                        new
                        {
                            ParkingSpotId = 20,
                            ParkingGarageId = 1,
                            Size = 4
                        },
                        new
                        {
                            ParkingSpotId = 21,
                            ParkingGarageId = 1,
                            Size = 4
                        },
                        new
                        {
                            ParkingSpotId = 22,
                            ParkingGarageId = 1,
                            Size = 4
                        },
                        new
                        {
                            ParkingSpotId = 23,
                            ParkingGarageId = 1,
                            Size = 4
                        },
                        new
                        {
                            ParkingSpotId = 24,
                            ParkingGarageId = 1,
                            Size = 4
                        },
                        new
                        {
                            ParkingSpotId = 25,
                            ParkingGarageId = 1,
                            Size = 4
                        },
                        new
                        {
                            ParkingSpotId = 26,
                            ParkingGarageId = 1,
                            Size = 4
                        },
                        new
                        {
                            ParkingSpotId = 27,
                            ParkingGarageId = 1,
                            Size = 4
                        },
                        new
                        {
                            ParkingSpotId = 28,
                            ParkingGarageId = 1,
                            Size = 4
                        },
                        new
                        {
                            ParkingSpotId = 29,
                            ParkingGarageId = 1,
                            Size = 4
                        },
                        new
                        {
                            ParkingSpotId = 30,
                            ParkingGarageId = 1,
                            Size = 4
                        },
                        new
                        {
                            ParkingSpotId = 31,
                            ParkingGarageId = 1,
                            Size = 4
                        },
                        new
                        {
                            ParkingSpotId = 32,
                            ParkingGarageId = 1,
                            Size = 4
                        },
                        new
                        {
                            ParkingSpotId = 33,
                            ParkingGarageId = 1,
                            Size = 4
                        },
                        new
                        {
                            ParkingSpotId = 34,
                            ParkingGarageId = 1,
                            Size = 4
                        },
                        new
                        {
                            ParkingSpotId = 35,
                            ParkingGarageId = 1,
                            Size = 4
                        },
                        new
                        {
                            ParkingSpotId = 36,
                            ParkingGarageId = 1,
                            Size = 4
                        },
                        new
                        {
                            ParkingSpotId = 37,
                            ParkingGarageId = 1,
                            Size = 4
                        },
                        new
                        {
                            ParkingSpotId = 38,
                            ParkingGarageId = 1,
                            Size = 4
                        },
                        new
                        {
                            ParkingSpotId = 39,
                            ParkingGarageId = 1,
                            Size = 4
                        },
                        new
                        {
                            ParkingSpotId = 40,
                            ParkingGarageId = 1,
                            Size = 4
                        },
                        new
                        {
                            ParkingSpotId = 41,
                            ParkingGarageId = 1,
                            Size = 4
                        },
                        new
                        {
                            ParkingSpotId = 42,
                            ParkingGarageId = 1,
                            Size = 4
                        },
                        new
                        {
                            ParkingSpotId = 43,
                            ParkingGarageId = 1,
                            Size = 4
                        },
                        new
                        {
                            ParkingSpotId = 44,
                            ParkingGarageId = 1,
                            Size = 4
                        },
                        new
                        {
                            ParkingSpotId = 45,
                            ParkingGarageId = 1,
                            Size = 4
                        },
                        new
                        {
                            ParkingSpotId = 46,
                            ParkingGarageId = 1,
                            Size = 4
                        },
                        new
                        {
                            ParkingSpotId = 47,
                            ParkingGarageId = 1,
                            Size = 4
                        },
                        new
                        {
                            ParkingSpotId = 48,
                            ParkingGarageId = 1,
                            Size = 4
                        },
                        new
                        {
                            ParkingSpotId = 49,
                            ParkingGarageId = 1,
                            Size = 4
                        },
                        new
                        {
                            ParkingSpotId = 50,
                            ParkingGarageId = 1,
                            Size = 4
                        },
                        new
                        {
                            ParkingSpotId = 51,
                            ParkingGarageId = 1,
                            Size = 4
                        },
                        new
                        {
                            ParkingSpotId = 52,
                            ParkingGarageId = 1,
                            Size = 4
                        },
                        new
                        {
                            ParkingSpotId = 53,
                            ParkingGarageId = 1,
                            Size = 4
                        },
                        new
                        {
                            ParkingSpotId = 54,
                            ParkingGarageId = 1,
                            Size = 4
                        },
                        new
                        {
                            ParkingSpotId = 55,
                            ParkingGarageId = 1,
                            Size = 4
                        },
                        new
                        {
                            ParkingSpotId = 56,
                            ParkingGarageId = 1,
                            Size = 4
                        },
                        new
                        {
                            ParkingSpotId = 57,
                            ParkingGarageId = 1,
                            Size = 4
                        },
                        new
                        {
                            ParkingSpotId = 58,
                            ParkingGarageId = 1,
                            Size = 4
                        },
                        new
                        {
                            ParkingSpotId = 59,
                            ParkingGarageId = 1,
                            Size = 4
                        },
                        new
                        {
                            ParkingSpotId = 60,
                            ParkingGarageId = 1,
                            Size = 4
                        },
                        new
                        {
                            ParkingSpotId = 61,
                            ParkingGarageId = 1,
                            Size = 4
                        },
                        new
                        {
                            ParkingSpotId = 62,
                            ParkingGarageId = 1,
                            Size = 4
                        },
                        new
                        {
                            ParkingSpotId = 63,
                            ParkingGarageId = 1,
                            Size = 4
                        },
                        new
                        {
                            ParkingSpotId = 64,
                            ParkingGarageId = 1,
                            Size = 4
                        },
                        new
                        {
                            ParkingSpotId = 65,
                            ParkingGarageId = 1,
                            Size = 4
                        },
                        new
                        {
                            ParkingSpotId = 66,
                            ParkingGarageId = 1,
                            Size = 4
                        },
                        new
                        {
                            ParkingSpotId = 67,
                            ParkingGarageId = 1,
                            Size = 4
                        },
                        new
                        {
                            ParkingSpotId = 68,
                            ParkingGarageId = 1,
                            Size = 4
                        },
                        new
                        {
                            ParkingSpotId = 69,
                            ParkingGarageId = 1,
                            Size = 4
                        },
                        new
                        {
                            ParkingSpotId = 70,
                            ParkingGarageId = 1,
                            Size = 4
                        },
                        new
                        {
                            ParkingSpotId = 71,
                            ParkingGarageId = 1,
                            Size = 4
                        },
                        new
                        {
                            ParkingSpotId = 72,
                            ParkingGarageId = 1,
                            Size = 4
                        },
                        new
                        {
                            ParkingSpotId = 73,
                            ParkingGarageId = 1,
                            Size = 4
                        },
                        new
                        {
                            ParkingSpotId = 74,
                            ParkingGarageId = 1,
                            Size = 4
                        },
                        new
                        {
                            ParkingSpotId = 75,
                            ParkingGarageId = 1,
                            Size = 4
                        },
                        new
                        {
                            ParkingSpotId = 76,
                            ParkingGarageId = 1,
                            Size = 4
                        },
                        new
                        {
                            ParkingSpotId = 77,
                            ParkingGarageId = 1,
                            Size = 4
                        },
                        new
                        {
                            ParkingSpotId = 78,
                            ParkingGarageId = 1,
                            Size = 4
                        },
                        new
                        {
                            ParkingSpotId = 79,
                            ParkingGarageId = 1,
                            Size = 4
                        },
                        new
                        {
                            ParkingSpotId = 80,
                            ParkingGarageId = 1,
                            Size = 4
                        },
                        new
                        {
                            ParkingSpotId = 81,
                            ParkingGarageId = 1,
                            Size = 4
                        },
                        new
                        {
                            ParkingSpotId = 82,
                            ParkingGarageId = 1,
                            Size = 4
                        },
                        new
                        {
                            ParkingSpotId = 83,
                            ParkingGarageId = 1,
                            Size = 4
                        },
                        new
                        {
                            ParkingSpotId = 84,
                            ParkingGarageId = 1,
                            Size = 4
                        },
                        new
                        {
                            ParkingSpotId = 85,
                            ParkingGarageId = 1,
                            Size = 4
                        },
                        new
                        {
                            ParkingSpotId = 86,
                            ParkingGarageId = 1,
                            Size = 4
                        },
                        new
                        {
                            ParkingSpotId = 87,
                            ParkingGarageId = 1,
                            Size = 4
                        },
                        new
                        {
                            ParkingSpotId = 88,
                            ParkingGarageId = 1,
                            Size = 4
                        },
                        new
                        {
                            ParkingSpotId = 89,
                            ParkingGarageId = 1,
                            Size = 4
                        },
                        new
                        {
                            ParkingSpotId = 90,
                            ParkingGarageId = 1,
                            Size = 4
                        },
                        new
                        {
                            ParkingSpotId = 91,
                            ParkingGarageId = 1,
                            Size = 4
                        },
                        new
                        {
                            ParkingSpotId = 92,
                            ParkingGarageId = 1,
                            Size = 4
                        },
                        new
                        {
                            ParkingSpotId = 93,
                            ParkingGarageId = 1,
                            Size = 4
                        },
                        new
                        {
                            ParkingSpotId = 94,
                            ParkingGarageId = 1,
                            Size = 4
                        },
                        new
                        {
                            ParkingSpotId = 95,
                            ParkingGarageId = 1,
                            Size = 4
                        },
                        new
                        {
                            ParkingSpotId = 96,
                            ParkingGarageId = 1,
                            Size = 4
                        },
                        new
                        {
                            ParkingSpotId = 97,
                            ParkingGarageId = 1,
                            Size = 4
                        },
                        new
                        {
                            ParkingSpotId = 98,
                            ParkingGarageId = 1,
                            Size = 4
                        },
                        new
                        {
                            ParkingSpotId = 99,
                            ParkingGarageId = 1,
                            Size = 4
                        },
                        new
                        {
                            ParkingSpotId = 100,
                            ParkingGarageId = 1,
                            Size = 4
                        });
                });

            modelBuilder.Entity("PragueParkingDataAccess.Vehicle", b =>
                {
                    b.Property<int>("VehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleId"), 1L, 1);

                    b.Property<DateTime>("Arrival")
                        .HasColumnType("datetime2");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ParkingSpotId")
                        .HasColumnType("int");

                    b.Property<string>("Registration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("Size")
                        .HasColumnType("tinyint");

                    b.HasKey("VehicleId");

                    b.HasIndex("ParkingSpotId");

                    b.ToTable("Vehicle");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Vehicle");
                });

            modelBuilder.Entity("PragueParkingDataAccess.Car", b =>
                {
                    b.HasBaseType("PragueParkingDataAccess.Vehicle");

                    b.HasDiscriminator().HasValue("Car");
                });

            modelBuilder.Entity("PragueParkingDataAccess.MC", b =>
                {
                    b.HasBaseType("PragueParkingDataAccess.Vehicle");

                    b.HasDiscriminator().HasValue("MC");
                });

            modelBuilder.Entity("PragueParkingDataAccess.ParkingSpot", b =>
                {
                    b.HasOne("PragueParkingDataAccess.ParkingGarage", "Garage")
                        .WithMany("ParkingSpots")
                        .HasForeignKey("ParkingGarageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Garage");
                });

            modelBuilder.Entity("PragueParkingDataAccess.Vehicle", b =>
                {
                    b.HasOne("PragueParkingDataAccess.ParkingSpot", "Parking")
                        .WithMany("Vehicles")
                        .HasForeignKey("ParkingSpotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parking");
                });

            modelBuilder.Entity("PragueParkingDataAccess.ParkingGarage", b =>
                {
                    b.Navigation("ParkingSpots");
                });

            modelBuilder.Entity("PragueParkingDataAccess.ParkingSpot", b =>
                {
                    b.Navigation("Vehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
